{"version":1,"defects":{"Unit\\RouterTest::there_are_no_routes_when_router_is_created":4,"Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":3,"Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":3,"Unit\\RouterTest::it_throws_route_not_found_exception":4,"Error":4,"Unit\\RouterTest::it_resolves_route":4},"times":{"Unit\\RouterTest::it_registers_a_route":0.004,"Unit\\RouterTest::it_registers_get_route":0.001,"Unit\\RouterTest::it_register_post_route":0.001,"Unit\\RouterTest::there_are_no_routes_when_router_is_created":0.001,"Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":0.002,"Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":0.001,"Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":0.001,"Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":0.001,"Unit\\RouterTest::it_throws_route_not_found_exception":0.002,"Error":0.003,"Unit\\RouterTest::it_resolves_route_from_closure":0.001,"Unit\\RouterTest::it_resolves_route":0.001}}